.TH "/Users/vadimpiven/Development/irrpoly/include/irrpoly/checker.hpp" 3 "Сб 16 Ноя 2019" "Version 1.0.0" "irrpoly" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/vadimpiven/Development/irrpoly/include/irrpoly/checker.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <thread>\fP
.br
\fC#include <cassert>\fP
.br
\fC#include <functional>\fP
.br
\fC#include <mutex>\fP
.br
\fC#include <condition_variable>\fP
.br

.SS "Классы"

.in +1c
.ti -1c
.RI "class \fBirrpoly::detail::sync\fP"
.br
.RI "Класс для управления мьютексом и условной переменной\&. "
.ti -1c
.RI "class \fBirrpoly::checker< value_type, result_type >\fP"
.br
.RI "Выполняет проверку на неприводимось и примитивность заданного многочлена над полем GF[P]\&. "
.in -1c
.SH "Подробное описание"
.PP 

.PP
\fBАвтор\fP
.RS 4
Vadim Piven vadim@piven.tech @license Free use of this library is permitted under the guidelines and in accordance with the MIT License (MIT)\&. @url https://github.com/irreducible-polynoms/irrpoly 
.RE
.PP

.SH "Автор"
.PP 
Автоматически создано Doxygen для irrpoly из исходного текста\&.
