.TH "/Users/vadimpiven/Development/irrpoly/checker.hpp" 3 "Ср 13 Ноя 2019" "Version 1.0.0" "irrpoly" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/vadimpiven/Development/irrpoly/checker.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <thread>\fP
.br
\fC#include <mutex>\fP
.br
\fC#include <condition_variable>\fP
.br
\fC#include 'polynomialgf\&.hpp'\fP
.br

.SS "Классы"

.in +1c
.ti -1c
.RI "class \fBdetail::sync\fP"
.br
.RI "Класс для управления мьютексом и условной переменной\&. "
.ti -1c
.RI "class \fBchecker< P >\fP"
.br
.RI "Выполняет проверку на неприводимось и примитивность заданного многочлена над полем GF[P]\&. "
.ti -1c
.RI "struct \fBchecker< P >::result_type\fP"
.br
.RI "Структура, представляющая результаты проверки многочлена\&. "
.ti -1c
.RI "class \fBchecker< P >::control_type\fP"
.br
.RI "Cлужебный класс, используется для выполнения проверки в несколько потоков\&. "
.in -1c
.SH "Подробное описание"
.PP 

.PP
\fBАвтор\fP
.RS 4
Vadim Piven vadim@piven.tech @license Free use of this library is permitted under the guidelines and in accordance with the MIT License (MIT)\&. @url https://github.com/irreducible-polynoms/irrpoly 
.RE
.PP

.SH "Автор"
.PP 
Автоматически создано Doxygen для irrpoly из исходного текста\&.
