.TH "dropbox::oxygen::nn_enable_shared_from_this< T >" 3 "Пн 1 Июн 2020" "Version 2.2.0" "irrpoly" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dropbox::oxygen::nn_enable_shared_from_this< T >
.SH SYNOPSIS
.br
.PP
.PP
Базовые классы:enable_shared_from_this< T >\&.
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "auto \fBnn_shared_from_this\fP () \-> \fBnn_shared_ptr\fP< T >"
.br
.ti -1c
.RI "auto \fBnn_shared_from_this\fP () const \-> \fBnn_shared_ptr\fP< const T >"
.br
.in -1c

.SH "Автор"
.PP 
Автоматически создано Doxygen для irrpoly из исходного текста\&.
