.TH "dropbox::oxygen::nn_enable_shared_from_this< T >" 3 "Mon Jun 15 2020" "Version 2.2.1" "irrpoly" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dropbox::oxygen::nn_enable_shared_from_this< T >
.SH SYNOPSIS
.br
.PP
.PP
Inherits enable_shared_from_this< T >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "auto \fBnn_shared_from_this\fP () \-> \fBnn_shared_ptr\fP< T >"
.br
.ti -1c
.RI "auto \fBnn_shared_from_this\fP () const \-> \fBnn_shared_ptr\fP< const T >"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for irrpoly from the source code\&.
