.TH "/Users/vadimpiven/Development/irrpoly/include/irrpoly/gf.hpp" 3 "Сб 16 Ноя 2019" "Version 1.0.0" "irrpoly" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/vadimpiven/Development/irrpoly/include/irrpoly/gf.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <algorithm>\fP
.br
\fC#include <array>\fP
.br
\fC#include <cstdint>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <random>\fP
.br
\fC#include <stdexcept>\fP
.br
\fC#include <type_traits>\fP
.br

.SS "Классы"

.in +1c
.ti -1c
.RI "class \fBirrpoly::gf< P >\fP"
.br
.in -1c
.SS "Функции"

.in +1c
.ti -1c
.RI "template<uint32_t P> ::std::ostream & \fBirrpoly::operator<<\fP (::std::ostream &os, const gf< P > &val)"
.br
.ti -1c
.RI "template<uint32_t P> ::std::istream & \fBirrpoly::operator>>\fP (::std::istream &is, gf< P > &val)"
.br
.in -1c
.SH "Подробное описание"
.PP 

.PP
\fBАвтор\fP
.RS 4
Vadim Piven vadim@piven.tech, Zimin Fedor zimfv@yandex.ru @license Free use of this library is permitted under the guidelines and in accordance with the MIT License (MIT)\&. @url https://github.com/irreducible-polynoms/irrpoly 
.RE
.PP

.SH "Автор"
.PP 
Автоматически создано Doxygen для irrpoly из исходного текста\&.
