.TH "irrpoly::gfn" 3 "Вт 21 Апр 2020" "Version 2.0.0" "irrpoly" \" -*- nroff -*-
.ad l
.nh
.SH NAME
irrpoly::gfn
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gf\&.hpp>\fP
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "\fBgfn\fP (const gf &field)"
.br
.RI "Конструктор по умолчанию, обнуляет переменную\&. "
.ti -1c
.RI "\fBgfn\fP (const gf &field, const uintmax_t val)"
.br
.ti -1c
.RI "\fBgfn\fP (const \fBgfn\fP &other)=default"
.br
.ti -1c
.RI "\fBgfn\fP (\fBgfn\fP &&other)=default"
.br
.ti -1c
.RI "\fBgfn\fP & \fBoperator=\fP (const \fBgfn\fP &other)"
.br
.ti -1c
.RI "uintmax_t \fBbase\fP () const"
.br
.ti -1c
.RI "\fBgfn\fP & \fBoperator=\fP (const uintmax_t other)"
.br
.ti -1c
.RI "const gf & \fBfield\fP () const"
.br
.ti -1c
.RI "uintmax_t \fBdata\fP () const"
.br
.RI "Возвращает значение класса в виде целого числа\&. "
.ti -1c
.RI "\fBgfn\fP \fBoperator+\fP () const"
.br
.ti -1c
.RI "\fBgfn\fP \fBoperator+\fP (const \fBgfn\fP &other) const"
.br
.ti -1c
.RI "\fBgfn\fP \fBoperator+\fP (const uintmax_t other) const"
.br
.ti -1c
.RI "\fBgfn\fP & \fBoperator+=\fP (const \fBgfn\fP &other)"
.br
.ti -1c
.RI "\fBgfn\fP \fBoperator+=\fP (const uintmax_t other)"
.br
.ti -1c
.RI "\fBgfn\fP & \fBoperator++\fP ()"
.br
.ti -1c
.RI "\fBgfn\fP \fBoperator++\fP (int) &"
.br
.ti -1c
.RI "\fBgfn\fP \fBoperator\-\fP () const"
.br
.ti -1c
.RI "\fBgfn\fP \fBoperator\-\fP (const \fBgfn\fP &other) const"
.br
.ti -1c
.RI "\fBgfn\fP \fBoperator\-\fP (const uintmax_t other) const"
.br
.ti -1c
.RI "\fBgfn\fP & \fBoperator\-=\fP (const \fBgfn\fP &other)"
.br
.ti -1c
.RI "\fBgfn\fP \fBoperator\-=\fP (const uintmax_t other)"
.br
.ti -1c
.RI "\fBgfn\fP & \fBoperator\-\-\fP ()"
.br
.ti -1c
.RI "\fBgfn\fP \fBoperator\-\-\fP (int) &"
.br
.ti -1c
.RI "\fBgfn\fP \fBoperator*\fP (const \fBgfn\fP &other) const"
.br
.ti -1c
.RI "\fBgfn\fP \fBoperator*\fP (const uintmax_t other) const"
.br
.ti -1c
.RI "\fBgfn\fP & \fBoperator*=\fP (const \fBgfn\fP &other)"
.br
.ti -1c
.RI "\fBgfn\fP \fBoperator*=\fP (const uintmax_t other)"
.br
.ti -1c
.RI "\fBgfn\fP \fBmul_inv\fP ()"
.br
.ti -1c
.RI "\fBgfn\fP \fBoperator/\fP (const \fBgfn\fP &other) const"
.br
.ti -1c
.RI "\fBgfn\fP \fBoperator/\fP (const uintmax_t other) const"
.br
.ti -1c
.RI "\fBgfn\fP & \fBoperator/=\fP (const \fBgfn\fP &other)"
.br
.ti -1c
.RI "\fBgfn\fP \fBoperator/=\fP (const uintmax_t other)"
.br
.ti -1c
.RI "bool \fBis_zero\fP () const"
.br
.RI "Проверяет равенство данного числа нулю\&. "
.ti -1c
.RI "\fBoperator bool\fP () const"
.br
.ti -1c
.RI "\fBgfn\fP & \fBset_zero\fP ()"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBgfn\fP &other) const"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const uintmax_t other) const"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBgfn\fP &other) const"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (const uintmax_t other) const"
.br
.ti -1c
.RI "bool \fBoperator>\fP (const \fBgfn\fP &other) const"
.br
.ti -1c
.RI "bool \fBoperator>\fP (const uintmax_t other) const"
.br
.ti -1c
.RI "bool \fBoperator>=\fP (const \fBgfn\fP &other) const"
.br
.ti -1c
.RI "bool \fBoperator>=\fP (const uintmax_t other) const"
.br
.ti -1c
.RI "bool \fBoperator<\fP (const \fBgfn\fP &other) const"
.br
.ti -1c
.RI "bool \fBoperator<\fP (const uintmax_t other) const"
.br
.ti -1c
.RI "bool \fBoperator<=\fP (const \fBgfn\fP &other) const"
.br
.ti -1c
.RI "bool \fBoperator<=\fP (const uintmax_t other) const"
.br
.in -1c
.SS "Открытые статические члены"

.in +1c
.ti -1c
.RI "static \fBgfn\fP \fBrandom\fP (const gf &field)"
.br
.RI "Генерирует случайное число в пределах [0, P-1]\&. "
.ti -1c
.RI "static uintmax_t \fBinto_num\fP (\fBgfn\fP &&val)"
.br
.in -1c
.SS "Друзья"

.in +1c
.ti -1c
.RI "\fBgfn\fP \fBoperator+\fP (uintmax_t, const \fBgfn\fP &)"
.br
.ti -1c
.RI "\fBgfn\fP \fBoperator\-\fP (uintmax_t, const \fBgfn\fP &)"
.br
.ti -1c
.RI "\fBgfn\fP \fBoperator*\fP (uintmax_t, const \fBgfn\fP &)"
.br
.ti -1c
.RI "\fBgfn\fP \fBoperator/\fP (uintmax_t, const \fBgfn\fP &)"
.br
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &, const \fBgfn\fP &)"
.br
.ti -1c
.RI "std::istream & \fBoperator>>\fP (std::istream &, \fBgfn\fP &)"
.br
.in -1c
.SH "Подробное описание"
.PP 
Класс gfn представляет число в поле GF[P] 
.PP
\fBПараметры шаблона\fP
.RS 4
\fIP\fP основание поля Галуа GF[P]\&. 
.RE
.PP


.SH "Автор"
.PP 
Автоматически создано Doxygen для irrpoly из исходного текста\&.
