.TH "irrpoly::detail::plus" 3 "Сб 16 Ноя 2019" "Version 1.0.0" "irrpoly" \" -*- nroff -*-
.ad l
.nh
.SH NAME
irrpoly::detail::plus
.SH SYNOPSIS
.br
.PP
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "template<class T , class U > T \fBoperator()\fP (T const &x, U const &y) const"
.br
.in -1c

.SH "Автор"
.PP 
Автоматически создано Doxygen для irrpoly из исходного текста\&.
