.TH "irrpoly::gf" 3 "Сб 4 Апр 2020" "Version 2.0.0" "irrpoly" \" -*- nroff -*-
.ad l
.nh
.SH NAME
irrpoly::gf \- Класс gf представляет поле Галуа\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gf\&.hpp>\fP
.SS "Открытые типы"

.in +1c
.ti -1c
.RI "using \fBvalue_type\fP = uintmax_t"
.br
.in -1c
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "value_type \fBbase\fP () const"
.br
.ti -1c
.RI "value_type \fBmul_inv\fP (value_type) const"
.br
.in -1c
.SS "Друзья"

.in +1c
.ti -1c
.RI "std::shared_ptr< \fBgf\fP > \fBmake_gf\fP (uintmax_t)"
.br
.in -1c
.SH "Подробное описание"
.PP 
Класс gf представляет поле Галуа\&. 

.SH "Автор"
.PP 
Автоматически создано Doxygen для irrpoly из исходного текста\&.
