.TH "irrpoly::gfpoly" 3 "Вт 28 Апр 2020" "Version 2.0.0" "irrpoly" \" -*- nroff -*-
.ad l
.nh
.SH NAME
irrpoly::gfpoly
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gfpoly\&.hpp>\fP
.SS "Открытые члены"

.in +1c
.ti -1c
.RI "auto \fBvalue\fP () const \-> std::vector< uintmax_t >"
.br
.ti -1c
.RI "auto \fBnormalize\fP () \-> \fBgfpoly\fP &"
.br
.ti -1c
.RI "\fBgfpoly\fP (const \fBgf\fP &field)"
.br
.ti -1c
.RI "\fBgfpoly\fP (const \fBgf\fP &field, const std::vector< uintmax_t > &l)"
.br
.ti -1c
.RI "auto \fBoperator=\fP (const std::vector< uintmax_t > &l) \-> \fBgfpoly\fP &"
.br
.ti -1c
.RI "\fBgfpoly\fP (const \fBgf\fP &field, std::initializer_list< uintmax_t > l)"
.br
.ti -1c
.RI "auto \fBoperator=\fP (std::initializer_list< uintmax_t > l) \-> \fBgfpoly\fP &"
.br
.ti -1c
.RI "\fBgfpoly\fP (const \fBgfpoly\fP &p)"
.br
.ti -1c
.RI "\fBgfpoly\fP (\fBgfpoly\fP &&p) noexcept"
.br
.ti -1c
.RI "auto \fBoperator=\fP (const \fBgfpoly\fP &p) \-> \fBgfpoly\fP &"
.br
.ti -1c
.RI "\fBgfpoly\fP (\fBgfn\fP value)"
.br
.ti -1c
.RI "auto \fBoperator=\fP (\fBgfn\fP value) \-> \fBgfpoly\fP &"
.br
.ti -1c
.RI "\fBgfpoly\fP (const \fBgf\fP &field, uintmax_t value)"
.br
.ti -1c
.RI "auto \fBoperator=\fP (uintmax_t value) \-> \fBgfpoly\fP &"
.br
.ti -1c
.RI "auto \fBfield\fP () const \-> const \fBgf\fP &"
.br
.ti -1c
.RI "auto \fBbase\fP () const \-> uintmax_t"
.br
.ti -1c
.RI "auto \fBsize\fP () const \-> uintmax_t"
.br
.ti -1c
.RI "auto \fBdegree\fP () const \-> uintmax_t"
.br
.ti -1c
.RI "auto \fBoperator[]\fP (uintmax_t i) \-> \fBgfn\fP &"
.br
.ti -1c
.RI "auto \fBoperator[]\fP (uintmax_t i) const \-> const \fBgfn\fP &"
.br
.ti -1c
.RI "auto \fBdata\fP () const \-> const std::vector< \fBgfn\fP > &"
.br
.ti -1c
.RI "auto \fBis_zero\fP () const \-> bool"
.br
.ti -1c
.RI "\fBoperator bool\fP () const"
.br
.ti -1c
.RI "auto \fBset_zero\fP () \-> \fBgfpoly\fP &"
.br
.ti -1c
.RI "template<class U > auto \fBoperator+=\fP (const U &value) \-> \fBgfpoly\fP &"
.br
.ti -1c
.RI "template<class U > auto \fBoperator\-=\fP (const U &value) \-> \fBgfpoly\fP &"
.br
.ti -1c
.RI "template<class U > auto \fBoperator*=\fP (const U &value) \-> \fBgfpoly\fP &"
.br
.ti -1c
.RI "template<class U > auto \fBoperator/=\fP (const U &value) \-> \fBgfpoly\fP &"
.br
.ti -1c
.RI "template<class U > auto \fBoperator%=\fP (const U &) \-> \fBgfpoly\fP &"
.br
.ti -1c
.RI "auto \fBoperator+=\fP (const \fBgfpoly\fP &value) \-> \fBgfpoly\fP &"
.br
.ti -1c
.RI "auto \fBoperator\-=\fP (const \fBgfpoly\fP &value) \-> \fBgfpoly\fP &"
.br
.ti -1c
.RI "auto \fBoperator*=\fP (const \fBgfpoly\fP &value) \-> \fBgfpoly\fP &"
.br
.ti -1c
.RI "auto \fBoperator/=\fP (const \fBgfpoly\fP &value) \-> \fBgfpoly\fP &"
.br
.ti -1c
.RI "auto \fBoperator%=\fP (const \fBgfpoly\fP &value) \-> \fBgfpoly\fP &"
.br
.ti -1c
.RI "template<typename U > auto \fBoperator>>=\fP (U const &n) \-> \fBgfpoly\fP &"
.br
.ti -1c
.RI "template<typename U > auto \fBoperator<<=\fP (U const &n) \-> \fBgfpoly\fP &"
.br
.in -1c
.SS "Открытые статические члены"

.in +1c
.ti -1c
.RI "static auto \fBrandom\fP (const \fBgf\fP &field, uintmax_t degree) \-> \fBgfpoly\fP"
.br
.RI "Генерирует случайный многочлен над полем GF[P] заданной степени\&. "
.in -1c
.SS "Друзья"

.in +1c
.ti -1c
.RI "auto \fBoperator\-\fP (\fBgfpoly\fP) \-> \fBgfpoly\fP"
.br
.ti -1c
.RI "auto \fBoperator*\fP (const \fBgfpoly\fP &, const \fBgfpoly\fP &) \-> \fBgfpoly\fP"
.br
.ti -1c
.RI "auto \fBoperator/\fP (const \fBgfpoly\fP &, const \fBgfpoly\fP &) \-> \fBgfpoly\fP"
.br
.ti -1c
.RI "auto \fBoperator%\fP (const \fBgfpoly\fP &, const \fBgfpoly\fP &) \-> \fBgfpoly\fP"
.br
.in -1c
.SH "Подробное описание"
.PP 
Класс gfpoly представляет многочлены над полем Галуа\&. Основан на классе polynomial из библиотеки Boost\&. 

.SH "Автор"
.PP 
Автоматически создано Doxygen для irrpoly из исходного текста\&.
