.TH "md___users_vadimpiven__development_irrpoly__r_e_a_d_m_e" 3 "Чт 14 Ноя 2019" "Version 1.0.0" "irrpoly" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md___users_vadimpiven__development_irrpoly__r_e_a_d_m_e \- Проверка многочленов на неприводимость и примитивность над заданным полем Галуа 

.SH "Требования"
.PP
Для работы программы необходимо наличие:
.IP "\(bu" 2
компилятора с поддержкой C++ 17
.IP "\(bu" 2
Cmake 3\&.8 для сборки проекта
.IP "\(bu" 2
64-битного процессора с как минимум двумя ядрами
.PP
.PP
При сборке данного проекта проверяется наличие библиотеки POSIX threads, в случае наличия программа с ней линкуется, в противном случае для многопоточности используются потоки \fCstd::thread\fP\&.
.SH "Состав"
.PP
Данная программа состоит из нескольких классов:
.IP "\(bu" 2
\fCgf<uint32_t P>\fP - класс чисел над полем Галуа заданной характеристики P
.IP "\(bu" 2
\fCpolynomial<typename T>\fP - класс арифметики многочленов
.IP "\(bu" 2
\fCpolynomialgf<uint32_t P>\fP - многочлены над полем Галуа, методы для их проверки на неприводимость и примитивность
.IP "\(bu" 2
\fCchecker<typename value_type, typename result_type>\fP - реализует многопоточность, принимает на вход три функции:
.IP "  \(bu" 4
\fCinput_func\fP - генерирует входные данные для \fCcheck_func\fP
.IP "  \(bu" 4
\fCcheck_func\fP - функция, работу которой и требуется распараллелить
.IP "  \(bu" 4
\fCcallback_func\fP - функция, обрабатывающая результат работы \fCcheck_func\fP
.PP

.PP
.PP
Всё необходимое для проверки многочленов на неприводимость и примитивность в несколько потоков погружено в \fCnamespace multithread\fP, кроме того, весь код заголовочных файлов помещён в \fCnamespace irrpoly\fP\&.
.PP
В файле \fCpolynomialgf\&.hpp\fP реализованы следующие алгоритмы:
.IP "\(bu" 2
\fCgcd\fP - поиск наибольшего общего делителя двух многочленов
.IP "\(bu" 2
\fCis_irreducible_berlekamp\fP - проверка многочлена на неприводимость методом Берлекампа
.IP "\(bu" 2
\fCis_irreducible_rabin\fP - проверка многочлена на неприводимость методом Рабина
.IP "\(bu" 2
\fCis_primitive_definition\fP - проверка многочлена на примитивность по определению
.PP
.SH "Документация"
.PP
Описание кода программы может быть найдено в папке [docs](docs) или на соответствующей странице \fCGitHub Pages\fP\&.
.PP
Сборка проекта и обновление документации может выполняться с использованием [Makefile](Makefile)\&. Доступные команды:
.IP "\(bu" 2
\fCmake debug\fP - сборка версии Debug
.IP "\(bu" 2
\fCmake release\fP - сборка версии Release
.IP "\(bu" 2
\fCmake docs\fP - перегенерация документации (требуется установленный Doxygen)
.PP
.SH "Использование"
.PP
Для использования программы требуется определиться с тем, какие именно многочлены нужно получить:
.IP "\(bu" 2
характеристика поля Галуа
.IP "\(bu" 2
степень многочленов
.IP "\(bu" 2
их количество
.IP "\(bu" 2
неприводимость или примитивность требуется проверять
.IP "\(bu" 2
порядок перебора многочленов
.PP
.PP
После чего требуется необходимым образом модифицировать функцию-шаблон в \fCmain\&.cpp\fP\&. Скорее всего потребуется реализовать собственный неслучайный способ подбора многочленов на проверку\&.
.PP
Для использования кода в других проектах рекомендуется использовать Git Submodules (\fCдокументация тут\fP)\&.
.PP
Единственный заголовочный файл, который потребуется подключить для использования данного кода - \fC#include 'irrpoly/polynomialgf\&.hpp'\fP (предполагается, что ваш код расположен в корневой папке репозитория, а данный код помещён в виде Git Submodule в папку \fCirrpoly\fP)\&.
.SH "Тестирование"
.PP
Тестовая функция \fCtest()\fP находится в \fCmain\&.cpp\fP\&. Она генерирует случайные многочлены и выполняет их проверку на неприводимость и примитивность\&. Затем эти многочлены копируюстя в файл [test_input](test_input) и загружаются в \fCWolfram Notebook\fP, и с помощью Wolfram Mathematica выполняется проверка полученного результата\&. Было проверено более 500 многочленов над различными полями Галуа, для всех них результат работы программы оказался правильным\&. При отсутствии Wilfram Mathematica можно воспользоваться его бесплатной альтернативой - Wolfram Engine for Developers (текст функций проверки приведён в виде комментария в \fCmain\&.cpp\fP)\&. 
